In [1]:
import numpy as np
import pandas as pd

Data Frames:

In [2]:

data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [3]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns= columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

slecting coloumn from data frame

In [4]:
df2[['Name','City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

creating a new column

In [5]:
df2['designation'] = ['engineer', 'doctor', 'cricketer','buisnessman']
df2

    Name  Age      City  Salary  designation
0   John   28  New York   65000     engineer
1   Anna   34     Paris   70000       doctor
2  Peter   29    Berlin   62000    cricketer
3  Linda   42    London   85000  buisnessman

removing a column:

In [7]:
df2.drop('designation',axis = 1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [8]:
df2.drop(['Name',"Age"],axis = True)

       City  Salary  designation
0  New York   65000     engineer
1     Paris   70000       doctor
2    Berlin   62000    cricketer
3    London   85000  buisnessman

In [9]:
df2.drop(0,axis=0)

    Name  Age    City  Salary  designation
1   Anna   34   Paris   70000       doctor
2  Peter   29  Berlin   62000    cricketer
3  Linda   42  London   85000  buisnessman

In [10]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selecting column:

In [11]:
df2.loc[[0,2]]

    Name  Age      City  Salary designation
0   John   28  New York   65000    engineer
2  Peter   29    Berlin   62000   cricketer

selecting subset of raws & column

In [12]:
df2

    Name  Age      City  Salary  designation
0   John   28  New York   65000     engineer
1   Anna   34     Paris   70000       doctor
2  Peter   29    Berlin   62000    cricketer
3  Linda   42    London   85000  buisnessman

In [13]:
df2.loc[[0,2]][["Salary","designation"]]

   Salary designation
0   65000    engineer
2   62000   cricketer

conditional selection

In [14]:
df2

    Name  Age      City  Salary  designation
0   John   28  New York   65000     engineer
1   Anna   34     Paris   70000       doctor
2  Peter   29    Berlin   62000    cricketer
3  Linda   42    London   85000  buisnessman

In [15]:
# i only want to see those people whose age are above 30:
df2[df2['Age']>30]

    Name  Age    City  Salary  designation
1   Anna   34   Paris   70000       doctor
3  Linda   42  London   85000  buisnessman

In [18]:
# i only want data of those whose age is above 30 and salary bmust be above 75000:

df2[(df2['Age']>30) & (df2['Salary']>7500)]

    Name  Age    City  Salary  designation
1   Anna   34   Paris   70000       doctor
3  Linda   42  London   85000  buisnessman