In [2]:
import numpy as np
import pandas as pd

In [29]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [4]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

Finding missing data:

In [5]:
 df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [6]:
 df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [7]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

removing missing data:

In [8]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [14]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [15]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

filling the missing data:

In [32]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [33]:
# filling data with 0
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [34]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [35]:
# filling data with multiple numbers:

values = {'A':100,'B':200,'C':300,'D':400}
df.fillna(value=values)

       A  B      C      D
0    1.0  1    1.0    1.0
1    2.0  2    2.0  400.0
2  100.0  3    3.0  400.0
3    4.0  4  300.0  400.0
4    5.0  5  300.0    5.0